# -*- coding: utf-8 -*-
"""Sub-plan8_M01 for NTU AI Project_SVM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhkACYeF1YgXL6eBU61ewNRZtCHXSOjA
"""

import io
from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import svm

# 上傳excel檔案
uploaded = files.upload()

df_data = pd.read_excel(io.BytesIO(uploaded['M01資料表.xlsx']))
print(len(df_data))
df_data.head()

##bins=[0, 18, 24, 31],
df_data['Label'] = pd.cut(x=df_data['MMSE Total (30)'], bins=[0, 27, 31],
                     labels=[1, 0])
print(df_data['Label'].value_counts())

y = df_data['Label'].astype('category')
df_data1 = df_data.drop(columns=['MMSE Total (30)', '研究一'])
X = df_data1.drop(labels=['Label'],axis=1).values # 移除Label並取得剩下欄位資料
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=77, stratify=y)

print('train shape:', X_train.shape)
print('test shape:', X_test.shape)

y = df_data['Label'].values
df_data1 = df_data.drop(columns=['MMSE Total (30)', '研究一'])
X = df_data1.drop(labels=['Label'],axis=1).values # 移除Label並取得剩下欄位資料
accu=[]
for i in range(1, 101):
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=i, stratify=y)
  clf=svm.SVC(kernel='rbf',C=1,gamma='auto')
  clf.fit(X_train,y_train)
  clf.predict(X_test)
  ac=clf.score(X_test, y_test)
  accu.append(ac)
round(sum(accu)/len(accu),2)



